added malware_signature
elastic/endpoint-package pull request #155
Opened 2021-06-30 15:07 UTC by gogochan

2021-06-30 17:56 UTC, gabriellandau commented on custom_subsets/elastic_endpoint/alerts/malware_event.yaml
> +            fields: "*"
Everything else here looks like this:
```suggestion
            fields: {}
```

2021-06-30 17:56 UTC, gabriellandau commented on custom_subsets/elastic_endpoint/alerts/malware_event.yaml
> +          malware_signature:
Should this go into memory_protection_event, since Memory Scan is presented to the user as part of Memory Protection?  https://github.com/elastic/endpoint-package/blob/c23a052ef81ea39ab2934e2e1ea5b32bff102196/custom_subsets/elastic_endpoint/alerts/memory_protection_event.yaml

2021-06-30 17:58 UTC, ferullo commented on custom_subsets/elastic_endpoint/alerts/malware_event.yaml
> +          malware_signature:
This should stay where it is at the very least for malware (FileScore) events. We could duplicate it to another location as well though I'd vote against that.

2021-06-30 18:25 UTC, ferullo commented on custom_subsets/elastic_endpoint/alerts/malware_event.yaml
> +          malware_signature:
I take it back. I now see you're commenting on `process.Ext.malware_signature` not `file.Exe.malware_signature`.

Currently Linux only sends file activity based malware (FileScore) alerts (open, write, etc) so wouldn't ever need this location. But Windows and macOS can send process based malware alerts (process start). So I still _think_ this is needed for Windows and macOS signature based FileScore alerts (and wonder why testing has been OK without this so far).

But that's only whether or not this update is beneficial to malware alerts. My presumption would be that a standardized key name for yara signature matches regardless of the protection type would be better than it going in different places for different alert types. But I don't feel strongly, if my presumption is wrong I'll stay silent.

2021-06-30 18:32 UTC, jonathan-buttner requested changes
Thanks for the PR Chan! Couple questions and changes:

From the example that Kevin linked ([memory_signature_agentTesla.json.zip](https://github.com/elastic/security-team/files/6650515/memory_signature_agentTesla.json.zip)) it looks like `memory_region` is included in `malware_signature`: 

```
"memory_region": {
                    "allocation_base": 4194304,
                    "allocation_protection": "RWX",
                    "allocation_size": 245760,
                    "allocation_type": "PRIVATE",
                    "bytes_address": 4194304,
                    "bytes_allocation_offset": 0,
```

do we need to update https://github.com/elastic/endpoint-package/blob/master/custom_schemas/custom_memory_region.yml#L11 to include it within this schema as well?

2021-06-30 18:32 UTC, jonathan-buttner commented on custom_subsets/elastic_endpoint/alerts/malware_event.yaml
> +            fields: "*"
We should update the docs on `"*"` vs `{}` because I always forget haha. `{}` only works when the field is a leaf aka if we only wanted `malware_signature.all_names` in the mapping we could write it like:

```
malware_signature:
  fields:
    all_names: {}
```
Since we want everything under `malware_signature` and `fields` is an array we have to use the `"*"` syntax like Chan has here.

2021-06-30 18:32 UTC, jonathan-buttner commented on custom_schemas/custom_malware_signature.yml
> +      type: object
From the example the structure of this field is:

```
                "primary": {
                    "matches": [
                        "TWFpbEFjY291bnRDb25maWd1cmF0aW9u",
                        ...
                    ],
                    "signature": {
                        "hash": {
                            "sha256": "60c031526f8c3099f324b9dccaad3e8e7fb60c85ef79237aa9917e128b072c14"
                        },
                        "id": "d3ac2b2f-14fc-4851-8a57-41032e386aeb",
                        "name": "Windows.Trojan.AgentTesla"
                    }
                },
```

Do we want `matches` and the other fields to be in the mapping so they can be searched for? If yes, then we'll want to add them here as well.

You could so something like this:

```
    - name: primary.matches
      level: custom
      type: keyword
      description: some description

    - name: primary.signature.hash.sha256
      level: custom
      type: keyword
      description: some description

    - name: primary.signature.id
      level: custom
      type: keyword
      description: some description

    - name: primary.signature.name
      level: custom
      type: keyword
      description: some description
```

ECS core does have a hash schema: https://github.com/elastic/ecs/blob/1.7/schemas/hash.yml so if the endpoint would ever ship more hashes under `primary.signature.hash` (say md5 etc) we might want to change https://github.com/elastic/endpoint-package/blob/master/custom_schemas/custom_hash.yml to just overlay them onto here that way you don't have to duplicate them.

2021-06-30 18:32 UTC, jonathan-buttner commented on custom_schemas/custom_malware_signature.yml
> +      type: array
In Elasticsearch there isn't an `array` type. Everything can be an array out of the box: https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-types.html#types-array-handling

Could we change this to the structure and type that will be contained within `secondary`? If `secondary` will be the exact same as `primary`, you could abstract it out to a new file and have it overlaid as both `primary` and `secondary` using the ECS `reuse` mechanism.

2021-06-30 20:25 UTC, gogochan commented on custom_subsets/elastic_endpoint/alerts/malware_event.yaml
> +          malware_signature:
Per our discussion, I will remove this line from this PR. We will add it back in 7.15

2021-06-30 20:26 UTC, gogochan commented on custom_schemas/custom_malware_signature.yml
> +      type: array
`secondary` will be a list of object that are subset of the `primary`. Should I just say `object` here then?

2021-06-30 20:54 UTC, gogochan commented
> do we need to update https://github.com/elastic/endpoint-package/blob/master/custom_schemas/custom_memory_region.yml#L11 to include it within this schema as well?

I'm not sure if we need to include them. IMO creating an Exception based on those values would be too much of information.

2021-07-01 13:27 UTC, jonathan-buttner commented on custom_schemas/custom_malware_signature.yml
> +      type: array
If we use `object` then users won't be able to search for it beyond just using a search based on its existence. If we don't expect users to search for the `secondary` fields then you could exclude it from the definition here. The only reason we want to define it in the endpoint package is so that users can search for it. If you want to include it just as a description of a field that could exist in an alert, we can add `enabled: false` (e.g. https://github.com/elastic/endpoint-package/blob/master/custom_schemas/custom_endpoint.yml#L28) that way Elasticsearch will not index it.

2021-07-01 13:32 UTC, jonathan-buttner commented
> > do we need to update https://github.com/elastic/endpoint-package/blob/master/custom_schemas/custom_memory_region.yml#L11 to include it within this schema as well?
> 
> I'm not sure if we need to include them. IMO creating an Exception based on those values would be too much of information.

I guess what I mean is, based on the example that Kevin gave I'm assuming the endpoint will send those memory region values. If we expect the user to want to search for alerts based on `malware_signature.memory_region.*` values then we'd need to include those in the mapping here. If we don't expect the user to search for them then we can leave them out. 

@kevinlog @pzl could you take a look at the mappings when you get a chance.

2021-07-01 13:33 UTC, jonathan-buttner commented on custom_schemas/custom_malware_signature.yml
> +      fields:
Let's remove the `fields:` here. That's only needed once at the top of these files.

2021-07-01 13:43 UTC, kevinlog commented
@jonathan-buttner thanks for bubbling this up.

> I guess what I mean is, based on the example that Kevin gave I'm assuming the endpoint will send those memory region values. If we expect the user to want to search for alerts based on `malware_signature.memory_region.*` values then we'd need to include those in the mapping here. If we don't expect the user to search for them then we can leave them out.

There are two questions to answer here:

1. Does the user need to search for alerts based on this field
2. Should the user be able to add Exceptions based on this field for this Alert
   - Implies we need it in the Index pattern

I don't think we need to index this field for searching.

However, we may want it included in the Index pattern so that we can write exceptions for it.

@gogochan @gabriellandau @ferullo any thoughts on writing Exceptions?

If we DO want to write Exceptions, we can `enabled: false` so that we don't index the field and include it in searches.

2021-07-01 14:14 UTC, ferullo commented
@joe-desimone has thoughts on what signature match fields should be available for exceptions.

2021-07-01 17:17 UTC, joe-desimone commented
I believe users should have the ability to search for and create exceptions from the following fields: `malware_signature.all_names`, `malware_signature.primary.signature.name`, and `malware_signature.primary.signature.id`, `malware_signature.memory_region.allocation_base`, `malware_signature.memory_region.allocation_protection`, `malware_signature.memory_region.allocation_size`, `malware_signature.memory_region.allocation_type`, `malware_signature.memory_region.region_protection`, `malware_signature.memory_region.region_size`, `malware_signature.memory_region.region_state`.

2021-07-01 17:46 UTC, dstepanic17 commented
@joe-desimone Here, are a couple fields I did not see on your list.  I believe the `region_base` maps to `allocation_base`, but might be confusing for users to not let them search or create exceptions on it.  I believe the other field `bytes_allocation_offset` can bring in unique data so might be useful for searching/exceptions. Everything else looks good.

-  `malware_signature.memory_region.region_base`
- `malware_signature.memory_region.bytes_allocation_offset`

2021-07-01 18:05 UTC, joe-desimone commented
> @joe-desimone Here, are a couple fields I did not see on your list. I believe the `region_base` maps to `allocation_base`, but might be confusing for users to not let them search or create exceptions on it. I believe the other field `bytes_allocation_offset` can bring in unique data so might be useful for searching/exceptions. Everything else looks good.
> 
> * `malware_signature.memory_region.region_base`
> * `malware_signature.memory_region.bytes_allocation_offset`

Thank you. I actually had allocation_base on there by mistake, and left off region_base intentionally. My thinking was these are going to be generally random so not too helpful from an exceptionlist point of view (but useful for response). allocation_offset I waffled on. In some situations it could be useful so I added it now.

Also, we dont have it yet but we should add malware_signature.memory_region.memory_pe.imphash to match shellcode alert schema more closely. We would want to search+exception on that as well so I added it to my original list.

2021-07-16 14:47 UTC, gogochan commented
> I believe users should have the ability to search for and create exceptions from the following fields: malware_signature.all_names, malware_signature.primary.signature.name, malware_signature.primary.signature.id, malware_signature.memory_region.allocation_protection, malware_signature.memory_region.allocation_size, malware_signature.memory_region.allocation_type, malware_signature.memory_region.region_protection, malware_signature.memory_region.region_size, malware_signature.memory_region.region_state, malware_signature.memory_region.memory_pe.imphash, malware_signature.memory_region.bytes_allocation_offset

Just want to point out that the current workflow does exception list checking before reading  process memory, thus it lacks `memory_signature.*` fields.

https://github.com/elastic/endpoint-dev/blob/master/Elastic/Plugins/MemoryProtection/Lib/MemoryScan.cpp#L472-L479

We can alter the behavior, but it means that we are checking the exception list after scanning process memory.

2021-07-16 15:24 UTC, gogochan commented
> do we need to update https://github.com/elastic/endpoint-package/blob/master/custom_schemas/custom_memory_region.yml#L11 to include it within this schema as well?

@jonathan-buttner  We will make a separate PR to address this. I've adjusted the PR per comments provided. Let me know if this is good.

2021-07-16 15:51 UTC, gabriellandau commented
@joe-desimone per our recent conversations, do you think we should put `malware_signature` under `memory_region` instead of vice-versa?

2021-07-16 16:00 UTC, jonathan-buttner requested changes
Left a few more comments about changes I think we need

2021-07-16 16:00 UTC, jonathan-buttner commented on custom_subsets/elastic_endpoint/alerts/malware_event.yaml
> +            fields: "*"
The `memory_region` custom schema I referenced above defines more fields then were discussed in the ticket. Not a huge deal but if you want to limit it to only include the ones asked for you can specify them explicitly here in the form of:

```
malware_signature:
  fields:
    memory_region:
      fields:
        fields_a: {}
        field_b: {}
        ...
```

2021-07-16 16:03 UTC, gogochan commented on custom_schemas/custom_malware_signature.yml
> +    - name: malware_signature.memory_region.allocation_protection
thanks... too many copy and pasting..

2021-07-16 16:05 UTC, gogochan commented on custom_schemas/custom_malware_signature.yml
> +    - name: malware_signature.memory_region.allocation_size
would it be okay even if fields defined under `memory_signature` is a subset of `memory_region`?

2021-07-16 16:06 UTC, gogochan commented on custom_subsets/elastic_endpoint/alerts/malware_event.yaml
> +            fields: "*"
I see that you answered my previous question here.

2021-07-16 16:12 UTC, gogochan commented on custom_subsets/elastic_endpoint/alerts/malware_event.yaml
> +            fields: "*"
since memory scan is part of memory protection, I'll move this under `memory_protection_event.yaml` instead

2021-07-16 16:48 UTC, gogochan commented
Thanks @jonathan-buttner for the suggestion. It looks better now.

2021-07-16 19:07 UTC, ferullo commented
> We can alter the behavior, but it means that we are checking the exception list after scanning process memory.

Endpoint should definitely check the exception list after it scans memory and can generate the alert but before it takes action. Checking exceptions earlier than this is a good optimization but this final check is always needed for all protections.

2021-07-16 19:18 UTC, jonathan-buttner approved these changes
Looks good! Just one question.

2021-07-16 19:18 UTC, jonathan-buttner commented on custom_schemas/custom_malware_signature.yml
> +      - file.Ext
Just a heads up it doesn't look like `malware_signature` is being placed under `file.Ext` 🤔  that might be because the file subset file doesn't include it 🤷‍♂️  is that ok?

2021-07-16 19:46 UTC, gogochan commented on custom_schemas/custom_malware_signature.yml
> +      - file.Ext
I updated the title. All fields added here are for Memory Protection plugin.

2021-07-17 13:08 UTC, joe-desimone commented
> > We can alter the behavior, but it means that we are checking the exception list after scanning process memory.
> 
> Endpoint should definitely check the exception list after it scans memory and can generate the alert but before it takes action. Checking exceptions earlier than this is a good optimization but this final check is always needed for all protections.

Agree here. I had the understanding that we do some early exceptionlist tests which would allow us better performance like https://github.com/elastic/global-security-exceptionlist/pull/257/files. Might be a good place for unit test.

2021-07-17 13:09 UTC, joe-desimone commented
> @joe-desimone per our recent conversations, do you think we should put `malware_signature` under `memory_region` instead of vice-versa?

Yes which would help makes things more consistent between shellcode alerts and memory scan alerts

2021-07-19 14:23 UTC, joe-desimone commented
> > @joe-desimone per our recent conversations, do you think we should put `malware_signature` under `memory_region` instead of vice-versa?
> 
> Yes which would help makes things more consistent between shellcode alerts and memory scan alerts

Created an issue to specifically discuss this proposal https://github.com/elastic/security-team/issues/1496

2021-07-19 14:40 UTC, gogochan commented
This may require further modification based on https://github.com/elastic/security-team/issues/1496

2021-07-19 20:45 UTC, gogochan commented
Added changes proposed in https://github.com/elastic/security-team/issues/1496

2021-07-19 21:37 UTC, gabriellandau requested changes

2021-07-19 21:37 UTC, gabriellandau commented on custom_schemas/custom_malware_signature.yml
> +      - memory_region
👍

2021-07-19 21:37 UTC, gabriellandau commented on custom_subsets/elastic_endpoint/alerts/memory_protection_event.yaml
> +              bytes_allocation_offset: {}
```suggestion
              bytes_allocation_offset: {}
              bytes_compressed: {}
              bytes_compressed_present: {}
              bytes_address: {}
              allocation_base: {}
```

2021-07-19 22:15 UTC, gogochan commented on custom_subsets/elastic_endpoint/alerts/memory_protection_event.yaml
> +              bytes_allocation_offset: {}
do we want all of these to be searchable?

2021-07-19 22:18 UTC, gogochan commented on custom_subsets/elastic_endpoint/alerts/memory_protection_event.yaml
> +              bytes_allocation_offset: {}
or having them here doesn't impact searchability?

2021-07-19 22:32 UTC, gabriellandau commented on custom_subsets/elastic_endpoint/alerts/memory_protection_event.yaml
> +              bytes_allocation_offset: {}
I'm going to defer to @jonathan-buttner on this, but AFAIK they need them in the subset in order for them to end up in the resulting schema.  Otherwise, the presence of these fields is a schema violation.  We can disabling indexing with the `index: false` directive: https://github.com/elastic/endpoint-package/blob/d28668a39ab33c4c7ac620b6c6e0807fe0d9dcfd/custom_schemas/custom_memory_region.yml#L57-L60

2021-07-28 16:38 UTC, gabriellandau approved these changes
I pushed changes that addressed my concerns.  LGTM.

2021-07-28 17:00 UTC, jonathan-buttner requested changes
Question about renaming `start_address_details`

2021-07-28 17:07 UTC, gabriellandau commented on custom_subsets/elastic_endpoint/alerts/memory_protection_event.yaml
> -              start_address_details:
> Has the endpoint already started populating these fields in 7.14 or prior?

Only for diagnostic.  The shellcode feature isn't going live until 7.15.

> If it has, do any of our detection rules use these fields?

Negative.  Not until 7.15.

2021-07-28 17:44 UTC, jonathan-buttner commented on custom_subsets/elastic_endpoint/alerts/memory_protection_event.yaml
> -              start_address_details:
Ok perfect! Thanks Gabe!

2021-07-28 17:44 UTC, jonathan-buttner approved these changes

2021-07-28 17:46 UTC, merged