Rule Detection Alert Schema
elastic/endpoint-package pull request #174
Opened 2021-08-13 18:33 UTC by brian-mckinney

2021-08-13 20:28 UTC, brian-mckinney commented
with these updates I am still getting validation errors for the `threat` and `responses` array.
```
DEBUG    root:ecs_helper.py:156 Document failed to pass ECS validator, the following terms did not pass schema check:
    Term: Value - Reason
        responses: [{'@timestamp': '2021-08-13T20:08:31.493036011Z', 'action': {'action': 'kill_process', 'field': 'process.entity_id', 'state': 0}, 'message': 'Success', 'process': {'entity_id': 'YWFhYWFhYWEtYWFhYS1hYWFhLWFhYWEtYWFhYWFhYWFhYWFhLTM0MDg2LTEzMjczMzU4OTExLjgxMzk0MDAw', 'name': 'sleep_9K9P1IOTXH', 'pid': 34086}, 'result': 0}] - Term not found in validation schema
        threat: [{'framework': 'EAF Test', 'tactic': {'id': 'EAF0001', 'name': 'Generic tactic', 'reference': 'https://elastic.co'}, 'technique': [{'id': 'XXXXXX', 'name': 'Process Creation', 'reference': 'https://elastic.co'}]}] - Term not found in validation schema
```

The format of the alert can be seen here: https://gist.github.com/brian-mckinney/8f3eb924a2374f231c75f211b9afb456

2021-08-15 22:16 UTC, ferullo requested changes
Shouldn't these fields be `Responses` not `responses` and `rule.Ext.severity` not `rule.severity` since they are not Endpoint extensions to ECS?

2021-08-16 12:59 UTC, ferullo commented on custom_schemas/custom_rule.yml
> +    - name: severity
`event.severity` already exists. What is this severity? It feels confusing to have two severities.

2021-08-18 17:13 UTC, brian-mckinney commented
This PR is superceded by https://github.com/elastic/endpoint-package/pull/175

2021-08-18 17:13 UTC, closed without merging