Update README.md
elastic/endpoint-package pull request #219
Opened 2021-11-20 04:08 UTC by umairkarel

Added some formatting to the readme

2021-12-03 14:47 UTC, pzl requested changes
@umairkarel please sign the Contributor Agreement if you would like us to add your PR

2021-12-03 14:47 UTC, pzl commented on README.md
> +- Edit/add custom schema files as needed to define any fields that doesn't exist in ECS core
the original line was correct, no change needed here

2021-12-13 14:38 UTC, pzl approved these changes
approved. As long as you follow the CLA procedures this can be merged

2021-12-13 16:22 UTC, umairkarel commented
> approved. As long as you follow the CLA procedures this can be merged

Definitely, I will follow the procedures.
I had tried to sign the agreement but, there was some problem, the page was not loading.

2022-03-01 13:40 UTC, pzl commented
Looks like this has stalled. If you'd like to contribute again, I'm happy to include your changes. Feel free to reopen once the CLA procedure is complete

2022-03-01 13:40 UTC, closed without merging