Add fields connected to rules and alerts
elastic/endpoint-package pull request #355
Opened 2023-03-20 12:06 UTC by tomsonpl

Closes: https://github.com/elastic/security-team/issues/5929

Not sure if we need rule_name, but from what I remember, it was agreed that we wanted it.

2023-03-20 12:12 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/endpoint-package-mbp%2FPR-355/detail/PR-355/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/endpoint-package-mbp%2FPR-355/detail/PR-355/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/endpoint-package-mbp%2FPR-355/detail/PR-355/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/endpoint-package-mbp%2FPR-355/detail/PR-355/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://endpoint-package_355.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-03-20T11:56:59.251Z&rangeTo=2023-03-20T12:16:59.251Z&transactionName=BUILD+endpoint-package-mbp%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=238c0f37cf6a3902d64e749e48dc4a96&transactionId=119525797e616eb0)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-03-20T12:06:59.251+0000


* Duration: 5 min 16 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














### Steps errors [![1](https://img.shields.io/badge/1%20-red)](https://fleet-ci.elastic.co/blue/organizations/jenkins/endpoint-package-mbp%2FPR-355/detail/PR-355/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `check for uncommitted build artifacts`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/endpoint-package-mbp/pipelines/PR-355/runs/1/steps/159/log/?start=0">here</a></li>
<li>Description: <code>git diff-index --exit-code HEAD --</code></l1>
</ul>
  
  </p>
  </details>



## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-03-20 19:56 UTC, tomsonpl commented
@pzl any idea if `rule_name` should be a `keyword` or just `text` ?

2023-03-20 20:06 UTC, pzl commented
> any idea if `rule_name` should be a `keyword` or just `text` ?

are we ever going to filter/search via name? I would imagine in filtering scenarios we probably know the rule_id and will be exact matching on that, right? 

If for some reason we will filter on the name, do we know the full string to match (e.g. find rule by name "Unusual Network Activity")? then keyword. If we expect to filter on partial word matches (e.g. match the previous rule name based on the search string "network") then text could be ok.

If we don't need to filter by name, then I would set it to keyword, and `index: false`. Or just don't map it at all

2023-03-22 15:39 UTC, tomsonpl commented
@pzl @dasansol92 could you take a look please? Thank you!

2023-03-22 15:47 UTC, pzl approved these changes
looks okay, I think things are added in the right place. Added @ashokaditya to review the intent of whats being added

2023-03-23 16:14 UTC, ashokaditya requested changes
I added some suggestions to update the mappings. Let me know if you need help or have questions.

2023-03-23 16:14 UTC, ashokaditya commented on custom_schemas/custom_endpoint_actions.yml
> +        List of alert ids that triggered the action
You'd also need to edit the `custom_subsets/elastic_endpoint/actions/actions.yaml` file. If you want the fields to also exist on the response doc then you need to edit the `custom_subsets/elastic_endpoint/action_responses/action_responses.yaml`.

2023-03-27 16:06 UTC, ashokaditya reviewed
Took another pass at reviewing. I have a question and suggestions.

2023-03-28 08:06 UTC, ashokaditya approved these changes

2023-03-28 08:06 UTC, ashokaditya commented on custom_schemas/custom_endpoint_actions.yml
> +        List of alert ids that triggered the action
Thanks for the changes. The fact that this is a `keyword` we can store an array of strings here s, so you can have multiple alert ids in the doc. Just that we should conform to ECS naming best practices.

2023-03-28 08:06 UTC, ashokaditya approved these changes

2023-03-28 10:25 UTC, tomsonpl commented
@ashokaditya Thank you for your feedback and bearing with me fixing it so many times :P

2023-03-28 12:22 UTC, merged

2023-04-25 21:11 UTC, elasticmachine commented
Package endpoint - 8.8.0 containing this change is available at https://epr.elastic.co/search?package=endpoint